import { NextResponse } from "next/server";
import { z } from "zod";
import { createAdminClient } from "@/lib/supabase/admin";
import { sendCourseRegistrationConfirmation } from "@/lib/email";
import { isValidCpf, normalizeCpf } from "@/lib/validation/cpf";

const schema = z.object({ courseId: z.string().uuid(), cpf: z.string().transform(normalizeCpf).refine(isValidCpf), birthDate: z.string().date() });
const messages: Record<string, string> = { registered: "Matrícula confirmada.", already_registered: "Você já está matriculado neste minicurso.", full: "Este minicurso está lotado.", schedule_conflict: "Este minicurso conflita com outra matrícula ativa.", registration_required: "Faça a inscrição geral antes de se matricular.", participant_not_found: "CPF ou data de nascimento não encontrados.", course_unavailable: "Minicurso indisponível." };
export async function POST(request: Request) { const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ message: "Dados de identificação inválidos." }, { status: 400 }); try { const service = createAdminClient(); const { data, error } = await service.rpc("register_for_course", { p_course_id: parsed.data.courseId, p_cpf: parsed.data.cpf, p_birth_date: parsed.data.birthDate }); if (error) throw error; if (data === "registered") { const [{ data: participant }, { data: course }] = await Promise.all([service.from("participants").select("full_name,email").eq("cpf", parsed.data.cpf).maybeSingle(), service.from("courses").select("title").eq("id", parsed.data.courseId).maybeSingle()]); if (participant?.email) void sendCourseRegistrationConfirmation({ to: participant.email, subject: "Matrícula confirmada", text: `Olá, ${participant.full_name}. Sua matrícula no minicurso ${course?.title ?? "selecionado"} foi confirmada.` }); } const message = messages[data] ?? "Não foi possível concluir a matrícula."; return NextResponse.json({ message }, { status: data === "registered" || data === "already_registered" ? 200 : 409 }); } catch { return NextResponse.json({ message: "Não foi possível concluir a matrícula." }, { status: 500 }); } }
