"use client";
import Image from "next/image";
import { useState } from "react";
type Course = { id: string; title: string; slug: string; description: string; instructor_name: string; instructor_bio: string | null; image_url: string | null; capacity: number; status: "draft" | "published" | "cancelled"; starts_at: string | null; ends_at: string | null; room: string | null };
type Draft = { title: string; slug: string; description: string; instructor_name: string; instructor_bio: string; capacity: string; status: Course["status"]; starts_at: string; ends_at: string; room: string };
const blank: Draft = { title: "", slug: "", description: "", instructor_name: "", instructor_bio: "", capacity: "", status: "draft", starts_at: "", ends_at: "", room: "" };
const toDraft = (c?: Course): Draft => c ? { title: c.title, slug: c.slug, description: c.description, instructor_name: c.instructor_name, instructor_bio: c.instructor_bio ?? "", capacity: String(c.capacity), status: c.status, starts_at: c.starts_at ? new Date(c.starts_at).toISOString().slice(0, 16) : "", ends_at: c.ends_at ? new Date(c.ends_at).toISOString().slice(0, 16) : "", room: c.room ?? "" } : blank;
const media = (value: string | null) => value ? (value.startsWith("http") ? value : `/api/media/${value}`) : null;
export default function CourseManager({ initial }: { initial: Course[] }) { const [items, setItems] = useState(initial); const [editing, setEditing] = useState<Course | null>(null); const [draft, setDraft] = useState<Draft>(blank); const [file, setFile] = useState<File | null>(null); const [errors, setErrors] = useState<Record<string, string>>({}); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const field = (name: keyof Draft, label: string, type = "text", required = true) => <label className="block text-sm font-medium">{label}<input required={required} name={name} type={type} min={name === "capacity" ? 1 : undefined} value={draft[name]} onChange={e => setDraft({ ...draft, [name]: e.target.value })} className={`mt-1 block w-full rounded border p-2 ${errors[name] ? "border-red-500" : ""}`}/>{errors[name] && <p className="mt-1 text-sm text-red-700">⚠ {errors[name]}</p>}</label>;
 async function upload() { if (!file) return editing?.image_url ?? null; const body = new FormData(); body.append("file", file); body.append("kind", "course"); const r = await fetch("/api/admin/uploads", { method: "POST", body }); const b = await r.json(); if (!r.ok) throw new Error(b.message); return b.path; }
 async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setErrors({}); setMessage(""); try { const image_url = await upload(); const payload = { ...draft, capacity: Number(draft.capacity), instructor_bio: draft.instructor_bio || null, room: draft.room || null, image_url, starts_at: draft.starts_at ? new Date(draft.starts_at).toISOString() : null, ends_at: draft.ends_at ? new Date(draft.ends_at).toISOString() : null }; const r = await fetch(editing ? `/api/admin/courses/${editing.id}` : "/api/admin/courses", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const b = await r.json(); if (!r.ok) { setErrors(b.fieldErrors ?? {}); setMessage(b.message ?? "Não foi possível salvar o minicurso."); return; } setMessage(b.message); setDraft(blank); setFile(null); setEditing(null); location.reload(); } catch (e) { setMessage(e instanceof Error ? e.message : "Falha no upload."); } finally { setBusy(false); } }
 const edit = (course: Course) => { setEditing(course); setDraft(toDraft(course)); setFile(null); setErrors({}); setMessage(""); };
 return <><form onSubmit={submit} className="mt-6 grid gap-4 rounded-xl border bg-white p-5 md:grid-cols-2"><div className="md:col-span-2 flex justify-between"><h2 className="text-lg font-bold">{editing ? "Editar minicurso" : "Novo minicurso"}</h2>{editing && <button type="button" onClick={() => { setEditing(null); setDraft(blank); setFile(null); }} className="text-sm underline">Cancelar edição</button>}</div>{message && <div role="alert" className="md:col-span-2 rounded border border-red-300 bg-red-50 p-3 text-red-800">{message}</div>}{field("title", "Título")}{field("slug", "Slug")}{field("instructor_name", "Ministrante")}{field("capacity", "Vagas", "number")}{field("starts_at", "Início", "datetime-local", false)}{field("ends_at", "Fim", "datetime-local", false)}{field("room", "Sala/local", "text", false)}<label>Status<select value={draft.status} onChange={e => setDraft({ ...draft, status: e.target.value as Course["status"] })} className="mt-1 block w-full rounded border p-2"><option value="draft">Rascunho</option><option value="published">Publicado</option><option value="cancelled">Cancelado</option></select></label><label>Imagem (opcional)<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e => setFile(e.target.files?.[0] ?? null)} className="mt-1 block w-full"/>{file && <span className="text-xs">{file.name}</span>}</label><label className="md:col-span-2">Descrição<textarea required value={draft.description} onChange={e => setDraft({ ...draft, description: e.target.value })} className="mt-1 block min-h-28 w-full rounded border p-2"/>{errors.description && <p className="text-sm text-red-700">⚠ {errors.description}</p>}</label><label className="md:col-span-2">Bio do ministrante<textarea value={draft.instructor_bio} onChange={e => setDraft({ ...draft, instructor_bio: e.target.value })} className="mt-1 block min-h-20 w-full rounded border p-2"/></label>{media(editing?.image_url ?? null) && <Image src={media(editing?.image_url ?? null)!} alt="Prévia do minicurso" width={320} height={180} unoptimized className="rounded"/>}<button disabled={busy} className="w-fit rounded bg-slate-900 px-4 py-2 text-white">{busy ? "Salvando…" : "Salvar minicurso"}</button></form><section className="mt-8 grid gap-4 md:grid-cols-2">{items.map(c => <article key={c.id} className="rounded-xl border bg-white p-4"><strong>{c.title}</strong><p className="mt-1 text-sm">{c.instructor_name} · {c.capacity} vagas · {c.status}</p><button onClick={() => edit(c)} className="mt-3 rounded border px-3 py-1 text-sm">Editar</button></article>)}</section></>; }
